"""
Comprehensive BNS/IPC Legal Database - Part 1: Person & Property Offences
"""

SECTIONS_PART1 = [
    {"id":"MURDER","bns":"101","ipc":"302","title":"Murder","desc":"Causing death with intention or knowledge of likely causing death.","punishment":"Death or Life Imprisonment + fine","keywords":"murder kill killed homicide death stabbed shot beaten strangled poisoned premeditated intentional killing","defenses":["Right of Private Defence (S.37 BNS)","Grave & Sudden Provocation","Insanity (S.22 BNS)","Accident without criminal intent"],"rights":["Right to Legal Counsel (Art 22)","Right against Self-Incrimination (Art 20(3))","Right to Fair Trial (Art 21)"]},
    {"id":"CULP_HOMICIDE","bns":"100","ipc":"299/304","title":"Culpable Homicide Not Amounting to Murder","desc":"Causing death without premeditation, in heat of passion or without full intention.","punishment":"Life imprisonment or up to 10 years + fine","keywords":"culpable homicide unintentional killing accidental death manslaughter negligent death rash act","defenses":["Lack of intention","Accident (S.23 BNS)","Sudden provocation","No knowledge of likely death"],"rights":["Right to Legal Counsel","Right to Bail (depending on facts)"]},
    {"id":"ATTEMPT_MURDER","bns":"109","ipc":"307","title":"Attempt to Murder","desc":"Doing any act with intention or knowledge that it could cause death, but death does not occur.","punishment":"Up to 10 years + fine. If hurt caused: Life imprisonment","keywords":"attempt murder tried to kill attempted killing attack with intent to kill life threatening attack nearly killed","defenses":["No intention to kill","Self-defense","Lack of knowledge act could cause death"],"rights":["Right to Legal Counsel","Right to Fair Investigation"]},
    {"id":"DOWRY_DEATH","bns":"80","ipc":"304B","title":"Dowry Death","desc":"Death of woman within 7 years of marriage under suspicious circumstances related to dowry demand.","punishment":"Not less than 7 years, extendable to Life","keywords":"dowry death bride burning dowry murder suspicious death after marriage in-laws killed wife","defenses":["Death was natural/accidental","No dowry demand was made","False complaint"],"rights":["Victim family: Right to immediate FIR","Right to investigation by senior officer"]},
    {"id":"ABETMENT_SUICIDE","bns":"108","ipc":"306","title":"Abetment of Suicide","desc":"Instigating, engaging in conspiracy, or aiding any person to commit suicide.","punishment":"Up to 10 years + fine","keywords":"abetment suicide instigated suicide drove to suicide harassment leading to suicide forced suicide mental torture suicide","defenses":["No direct instigation","Deceased had independent reasons","No mens rea"],"rights":["Right to Legal Counsel","Right to Bail application"]},
    {"id":"HURT","bns":"115","ipc":"323","title":"Voluntarily Causing Hurt","desc":"Causing bodily pain, disease or infirmity to any person intentionally.","punishment":"Up to 1 year or fine up to Rs.10,000 or both","keywords":"hurt hit punch slap beat beating physical violence bodily harm injured simple assault minor injury","defenses":["Self-defense","Consent","Provocation","Accident"],"rights":["Right to file counter-complaint","Right to Bail (bailable)","Right to Legal Counsel"]},
    {"id":"GRIEVOUS_HURT","bns":"117","ipc":"325","title":"Voluntarily Causing Grievous Hurt","desc":"Causing fracture, loss of vision/hearing, disfiguration, or danger to life.","punishment":"Up to 7 years + fine","keywords":"grievous hurt serious injury fracture broken bone loss of eye ear disfigure permanent disability dangerous injury","defenses":["Self-defense","Provocation","No intention to cause grievous hurt"],"rights":["Right to Medical Examination","Right to Legal Counsel"]},
    {"id":"HURT_WEAPON","bns":"118","ipc":"326","title":"Grievous Hurt by Dangerous Weapons","desc":"Causing grievous hurt using shooting, stabbing, cutting instrument or any weapon likely to cause death.","punishment":"Life imprisonment or up to 10 years + fine","keywords":"weapon knife stabbing rod bat iron pipe axe sword gun shot acid attack dangerous weapon attack","defenses":["Self-defense with proportionate force","Provocation","Weapon was not inherently dangerous"],"rights":["Right to Medical Examination","Right to Legal Counsel","Right to know grounds of arrest"]},
    {"id":"ACID_ATTACK","bns":"124","ipc":"326A","title":"Acid Attack","desc":"Causing permanent or partial damage by throwing acid or similar substance.","punishment":"Not less than 10 years, extendable to Life + fine","keywords":"acid attack acid thrown corrosive substance chemical attack burn face acid victim","defenses":["False accusation","Mistaken identity","Accidental spill"],"rights":["Victim: Right to free medical treatment","Victim: Right to compensation","Right to speedy trial"]},
    {"id":"KIDNAPPING","bns":"137","ipc":"359/363","title":"Kidnapping","desc":"Taking minor under 16 (boy) or 18 (girl) or person of unsound mind from lawful guardian without consent.","punishment":"Up to 7 years + fine","keywords":"kidnap kidnapped abduction child missing child taken away minor taken enticed","defenses":["Person left voluntarily","Person is a major and consented","Custody dispute"],"rights":["Right to immediate FIR","Right to police search operation","Right to Legal Counsel"]},
    {"id":"ABDUCTION","bns":"137-140","ipc":"362/364/366","title":"Abduction","desc":"Compelling person by force or deceit to go from any place. Includes abduction for ransom, murder, or marriage.","punishment":"7 years to Life depending on purpose","keywords":"abduction forced taken held captive hostage ransom kidnap for ransom forced marriage abduct woman","defenses":["No force or deceit used","Person came willingly","Mistaken identity"],"rights":["Right to FIR","Right to police protection","Right to Legal Counsel"]},
    {"id":"WRONGFUL_RESTRAINT","bns":"126","ipc":"339/340","title":"Wrongful Restraint / Confinement","desc":"Preventing any person from proceeding in any direction or confining them to a limited space.","punishment":"Restraint: up to 1 month or Rs.500. Confinement: up to 1 year or Rs.1000","keywords":"wrongful restraint confinement locked up imprisoned held against will detained illegally not allowed to leave trapped","defenses":["Lawful authority to detain","Person was not actually restrained","Consent"],"rights":["Right to habeas corpus","Right to immediate release","Right to Legal Counsel"]},
    {"id":"ASSAULT_WOMAN","bns":"74","ipc":"354","title":"Assault on Woman to Outrage Modesty","desc":"Using criminal force on any woman intending to outrage or knowing it to be likely to outrage her modesty.","punishment":"1 to 5 years + fine","keywords":"molest molestation groping touched inappropriately outrage modesty woman assault indecent touch","defenses":["False accusation","No criminal force used","No intention to outrage modesty"],"rights":["Victim: Statement by female officer","Right to Legal Counsel","Right to privacy during trial"]},
    {"id":"SEXUAL_HARASSMENT","bns":"75","ipc":"354A","title":"Sexual Harassment","desc":"Physical contact, demand for sexual favours, showing pornography, making sexual remarks.","punishment":"Up to 3 years + fine (for remarks). Up to 5 years (for physical contact/demand)","keywords":"sexual harassment workplace harassment sexual remarks unwanted advances demand sexual favour showing pornography eve teasing","defenses":["False accusation","Misunderstanding of context","No sexual intent"],"rights":["Right to file complaint with Internal Complaints Committee","Right to file FIR","Right to Legal Counsel"]},
    {"id":"STALKING","bns":"78","ipc":"354D","title":"Stalking","desc":"Following a woman, contacting her repeatedly despite disinterest, monitoring her internet/electronic communication.","punishment":"First offence: up to 3 years + fine. Repeat: up to 5 years + fine","keywords":"stalking following repeatedly contacting unwanted messages cyber stalking watching monitoring tracking","defenses":["Lawful purpose for following","No repeated pattern","Person consented to contact"],"rights":["Right to immediate FIR","Right to restraining order","Right to Legal Counsel"]},
    {"id":"VOYEURISM","bns":"77","ipc":"354C","title":"Voyeurism","desc":"Watching or capturing image of a woman engaging in a private act without her consent.","punishment":"First offence: 1-3 years + fine. Repeat: 3-7 years + fine","keywords":"voyeurism peeping hidden camera secretly recording private photos without consent bathroom camera spy camera","defenses":["No such act was committed","Consent existed","False accusation"],"rights":["Victim: Right to privacy","Right to destruction of captured material","Right to Legal Counsel"]},
    {"id":"RAPE","bns":"63","ipc":"375/376","title":"Rape","desc":"Sexual intercourse with woman against her will, without consent, by coercion, with minor, or when she cannot give consent.","punishment":"Not less than 10 years, extendable to Life + fine","keywords":"rape sexual assault forced intercourse sexual violence victim of rape minor rape child sexual abuse","defenses":["Consent (where legally applicable, not for minors)","False accusation","Alibi","Lack of evidence"],"rights":["Victim: Statement by female officer","Victim: Medical exam by female doctor","Victim: Free legal aid","Accused: Presumption of innocence"]},
    {"id":"GANG_RAPE","bns":"70","ipc":"376D","title":"Gang Rape","desc":"Rape committed by one or more persons acting in furtherance of common intention.","punishment":"Not less than 20 years, extendable to Life (remainder of natural life) + fine","keywords":"gang rape group rape multiple persons rape collective sexual assault","defenses":["Alibi","Mistaken identity","False implication"],"rights":["Victim: In-camera trial","Victim: Identity protection","Right to speedy trial"]},
    {"id":"THEFT","bns":"303","ipc":"378/379","title":"Theft","desc":"Dishonestly taking moveable property out of someone's possession without consent.","punishment":"Up to 3 years or fine or both","keywords":"theft stolen stole stealing shoplifting pick pocket mobile stolen bag snatched took my belongings property taken","defenses":["Claim of right over property","Owner's consent","No dishonest intention","Mistaken identity"],"rights":["Right to Bail (bailable)","Right to Legal Counsel","Right to be produced before Magistrate within 24 hours"]},
    {"id":"ROBBERY","bns":"309","ipc":"392","title":"Robbery","desc":"Theft with use of force, causing death/hurt/wrongful restraint to commit or retain stolen property.","punishment":"Up to 10 years + fine. On highway at night: up to 14 years","keywords":"robbery armed robbery mugging robbed at gunpoint snatching with force violent theft hold up loot","defenses":["Alibi","Mistaken identity","Duress","No force used"],"rights":["Right to Legal Counsel","Right to Fair Investigation","Right to be informed of charges"]},
    {"id":"DACOITY","bns":"310","ipc":"395/396","title":"Dacoity","desc":"Robbery committed by 5 or more persons. If murder committed during dacoity, all are liable.","punishment":"Life imprisonment or 10 years + fine. With murder: Death or Life","keywords":"dacoity gang robbery five or more persons armed gang loot dacoit organized robbery","defenses":["Was not part of the group","No common intention","Duress/coercion to participate"],"rights":["Right to Legal Counsel","Right to Fair Trial"]},
    {"id":"EXTORTION","bns":"308","ipc":"383/384","title":"Extortion","desc":"Putting any person in fear of injury to dishonestly induce surrender of property or valuable security.","punishment":"Up to 3 years or fine or both","keywords":"extortion blackmail threatening for money demanding money protection money hafta rangdari forced to pay threatening","defenses":["No threat was made","Lawful claim to money","False accusation"],"rights":["Right to FIR","Right to Police Protection","Right to Legal Counsel"]},
    {"id":"CHEATING","bns":"318","ipc":"420","title":"Cheating","desc":"Deceiving a person dishonestly to induce delivery of property or altering/destroying valuable security.","punishment":"Up to 7 years + fine","keywords":"cheating fraud scam deceived duped con financial fraud swindled fake deal cheated money tricked false promise","defenses":["No dishonest intention","Civil dispute not cheating","Misunderstanding not deception","Breach of contract ≠ cheating"],"rights":["Right to file FIR","Right to approach Consumer Forum","Right to Legal Counsel"]},
    {"id":"FORGERY","bns":"336","ipc":"463/465","title":"Forgery","desc":"Making a false document with intent to cause damage, support a claim, or induce someone to part with property.","punishment":"Up to 2 years or fine or both","keywords":"forgery forged document fake signature false document counterfeit fabricated document fake certificate fake degree","defenses":["No fraudulent intent","Document was genuine","Mistake in preparation"],"rights":["Right to Legal Counsel","Right to document examination"]},
    {"id":"CRIMINAL_BREACH_TRUST","bns":"316","ipc":"405/406","title":"Criminal Breach of Trust","desc":"Dishonestly misappropriating or converting to own use property entrusted to the accused.","punishment":"Up to 3 years or fine or both. By public servant/banker: up to 10 years + fine","keywords":"breach of trust misappropriation embezzlement funds misused money entrusted stolen trust money company funds diverted","defenses":["No entrustment existed","Honest use of property","Accounting error not misappropriation"],"rights":["Right to Legal Counsel","Right to Bail"]},
]
