"""
Comprehensive BNS/IPC Legal Database - Optimized Unified Edition
================================================================
Contains all Person, Property, Public Order, and Special Law sections.
"""

LEGAL_SECTIONS = [
    # --- PART 1: PERSON & PROPERTY OFFENCES ---
    {"id":"MURDER","bns":"101","ipc":"302","title":"Murder","desc":"Causing death with intention or knowledge of likely causing death.","punishment":"Death or Life Imprisonment + fine","keywords":"murder kill killed homicide death stabbed shot beaten strangled poisoned premeditated intentional killing","defenses":["Right of Private Defence (S.37 BNS)","Grave & Sudden Provocation","Insanity (S.22 BNS)","Accident without criminal intent"],"rights":["Right to Legal Counsel (Art 22)","Right against Self-Incrimination (Art 20(3))","Right to Fair Trial (Art 21)"]},
    {"id":"CULP_HOMICIDE","bns":"100","ipc":"299/304","title":"Culpable Homicide Not Amounting to Murder","desc":"Causing death without premeditation, in heat of passion or without full intention.","punishment":"Life imprisonment or up to 10 years + fine","keywords":"culpable homicide unintentional killing accidental death manslaughter negligent death rash act","defenses":["Lack of intention","Accident (S.23 BNS)","Sudden provocation","No knowledge of likely death"],"rights":["Right to Legal Counsel","Right to Bail (depending on facts)"]},
    {"id":"ATTEMPT_MURDER","bns":"109","ipc":"307","title":"Attempt to Murder","desc":"Doing any act with intention or knowledge that it could cause death, but death does not occur.","punishment":"Up to 10 years + fine. If hurt caused: Life imprisonment","keywords":"attempt murder tried to kill attempted killing attack with intent to kill life threatening attack nearly killed","defenses":["No intention to kill","Self-defense","Lack of knowledge act could cause death"],"rights":["Right to Legal Counsel","Right to Fair Investigation"]},
    {"id":"DOWRY_DEATH","bns":"80","ipc":"304B","title":"Dowry Death","desc":"Death of woman within 7 years of marriage under suspicious circumstances related to dowry demand.","punishment":"Not less than 7 years, extendable to Life","keywords":"dowry death bride burning dowry murder suspicious death after marriage in-laws killed wife","defenses":["Death was natural/accidental","No dowry demand was made","False complaint"],"rights":["Victim family: Right to immediate FIR","Right to investigation by senior officer"]},
    {"id":"ABETMENT_SUICIDE","bns":"108","ipc":"306","title":"Abetment of Suicide","desc":"Instigating, engaging in conspiracy, or aiding any person to commit suicide.","punishment":"Up to 10 years + fine","keywords":"abetment suicide instigated suicide drove to suicide harassment leading to suicide forced suicide mental torture suicide","defenses":["No direct instigation","Deceased had independent reasons","No mens rea"],"rights":["Right to Legal Counsel","Right to Bail application"]},
    {"id":"HURT","bns":"115","ipc":"323","title":"Voluntarily Causing Hurt","desc":"Causing bodily pain, disease or infirmity to any person intentionally.","punishment":"Up to 1 year or fine up to Rs.10,000 or both","keywords":"hurt hit punch slap beat beating physical violence bodily harm injured simple assault minor injury","defenses":["Self-defense","Consent","Provocation","Accident"],"rights":["Right to file counter-complaint","Right to Bail (bailable)","Right to Legal Counsel"]},
    {"id":"GRIEVOUS_HURT","bns":"117","ipc":"325","title":"Voluntarily Causing Grievous Hurt","desc":"Causing fracture, loss of vision/hearing, disfiguration, or danger to life.","punishment":"Up to 7 years + fine","keywords":"grievous hurt serious injury fracture broken bone loss of eye ear disfigure permanent disability dangerous injury","defenses":["Self-defense","Provocation","No intention to cause grievous hurt"],"rights":["Right to Medical Examination","Right to Legal Counsel"]},
    {"id":"HURT_WEAPON","bns":"118","ipc":"326","title":"Grievous Hurt by Dangerous Weapons","desc":"Causing grievous hurt using shooting, stabbing, cutting instrument or any weapon likely to cause death.","punishment":"Life imprisonment or up to 10 years + fine","keywords":"weapon knife stabbing rod bat iron pipe axe sword gun shot acid attack dangerous weapon attack","defenses":["Self-defense with proportionate force","Provocation","Weapon was not inherently dangerous"],"rights":["Right to Medical Examination","Right to Legal Counsel","Right to know grounds of arrest"]},
    {"id":"ACID_ATTACK","bns":"124","ipc":"326A","title":"Acid Attack","desc":"Causing permanent or partial damage by throwing acid or similar substance.","punishment":"Not less than 10 years, extendable to Life + fine","keywords":"acid attack acid thrown corrosive substance chemical attack burn face acid victim","defenses":["False accusation","Mistaken identity","Accidental spill"],"rights":["Victim: Right to free medical treatment","Victim: Right to compensation","Right to speedy trial"]},
    {"id":"KIDNAPPING","bns":"137","ipc":"359/363","title":"Kidnapping","desc":"Taking minor under 16 (boy) or 18 (girl) or person of unsound mind from lawful guardian without consent.","punishment":"Up to 7 years + fine","keywords":"kidnap kidnapped abduction child missing child taken away minor taken enticed","defenses":["Person left voluntarily","Person is a major and consented","Custody dispute"],"rights":["Right to immediate FIR","Right to police search operation","Right to Legal Counsel"]},
    {"id":"ABDUCTION","bns":"137-140","ipc":"362/364/366","title":"Abduction","desc":"Compelling person by force or deceit to go from any place. Includes abduction for ransom, murder, or marriage.","punishment":"7 years to Life depending on purpose","keywords":"abduction forced taken held captive hostage ransom kidnap for ransom forced marriage abduct woman","defenses":["No force or deceit used","Person came willingly","Mistaken identity"],"rights":["Right to FIR","Right to police protection","Right to Legal Counsel"]},
    {"id":"WRONGFUL_RESTRAINT","bns":"126","ipc":"339/340","title":"Wrongful Restraint / Confinement","desc":"Preventing any person from proceeding in any direction or confining them to a limited space.","punishment":"Restraint: up to 1 month or Rs.500. Confinement: up to 1 year or Rs.1000","keywords":"wrongful restraint confinement locked up imprisoned held against will detained illegally not allowed to leave trapped","defenses":["Lawful authority to detain","Person was not actually restrained","Consent"],"rights":["Right to habeas corpus","Right to immediate release","Right to Legal Counsel"]},
    {"id":"ASSAULT_WOMAN","bns":"74","ipc":"354","title":"Assault on Woman to Outrage Modesty","desc":"Using criminal force on any woman intending to outrage or knowing it to be likely to outrage her modesty.","punishment":"1 to 5 years + fine","keywords":"molest molestation groping touched inappropriately outrage modesty woman assault indecent touch","defenses":["False accusation","No criminal force used","No intention to outrage modesty"],"rights":["Victim: Statement by female officer","Right to Legal Counsel","Right to privacy during trial"]},
    {"id":"SEXUAL_HARASSMENT","bns":"75","ipc":"354A","title":"Sexual Harassment","desc":"Physical contact, demand for sexual favours, showing pornography, making sexual remarks.","punishment":"Up to 3 years + fine (for remarks). Up to 5 years (for physical contact/demand)","keywords":"sexual harassment workplace harassment sexual remarks unwanted advances demand sexual favour showing pornography eve teasing","defenses":["False accusation","Misunderstanding of context","No sexual intent"],"rights":["Right to file complaint with Internal Complaints Committee","Right to file FIR","Right to Legal Counsel"]},
    {"id":"STALKING","bns":"78","ipc":"354D","title":"Stalking","desc":"Following a woman, contacting her repeatedly despite disinterest, monitoring her internet/electronic communication.","punishment":"First offence: up to 3 years + fine. Repeat: up to 5 years + fine","keywords":"stalking following repeatedly contacting unwanted messages cyber stalking watching monitoring tracking","defenses":["Lawful purpose for following","No repeated pattern","Person consented to contact"],"rights":["Right to immediate FIR","Right to restraining order","Right to Legal Counsel"]},
    {"id":"VOYEURISM","bns":"77","ipc":"354C","title":"Voyeurism","desc":"Watching or capturing image of a woman engaging in a private act without her consent.","punishment":"First offence: 1-3 years + fine. Repeat: 3-7 years + fine","keywords":"voyeurism peeping hidden camera secretly recording private photos without consent bathroom camera spy camera","defenses":["No such act was committed","Consent existed","False accusation"],"rights":["Victim: Right to privacy","Right to destruction of captured material","Right to Legal Counsel"]},
    {"id":"RAPE","bns":"63","ipc":"375/376","title":"Rape","desc":"Sexual intercourse with woman against her will, without consent, by coercion, with minor, or when she cannot give consent.","punishment":"Not less than 10 years, extendable to Life + fine","keywords":"rape sexual assault forced intercourse sexual violence victim of rape minor rape child sexual abuse","defenses":["Consent (where legally applicable, not for minors)","False accusation","Alibi","Lack of evidence"],"rights":["Victim: Statement by female officer","Victim: Medical exam by female doctor","Victim: Free legal aid","Accused: Presumption of innocence"]},
    {"id":"THIEF","bns":"303","ipc":"378/379","title":"Theft","desc":"Dishonestly taking moveable property out of someone's possession without consent.","punishment":"Up to 3 years or fine or both","keywords":"theft stolen stole stealing shoplifting pick pocket mobile stolen bag snatched took my belongings property taken","defenses":["Claim of right over property","Owner's consent","No dishonest intention","Mistaken identity"],"rights":["Right to Bail (bailable)","Right to Legal Counsel","Right to be produced before Magistrate within 24 hours"]},
    {"id":"ROBBERY","bns":"309","ipc":"392","title":"Robbery","desc":"Theft with use of force, causing death/hurt/wrongful restraint to commit or retain stolen property.","punishment":"Up to 10 years + fine. On highway at night: up to 14 years","keywords":"robbery armed robbery mugging robbed at gunpoint snatching with force violent theft hold up loot","defenses":["Alibi","Mistaken identity","Duress","No force used"],"rights":["Right to Legal Counsel","Right to Fair Investigation","Right to be informed of charges"]},
    {"id":"EXTORTION","bns":"308","ipc":"383/384","title":"Extortion","desc":"Putting any person in fear of injury to dishonestly induce surrender of property or valuable security.","punishment":"Up to 3 years or fine or both","keywords":"extortion blackmail threatening for money demanding money protection money hafta rangdari forced to pay threatening","defenses":["No threat was made","Lawful claim to money","False accusation"],"rights":["Right to FIR","Right to Police Protection","Right to Legal Counsel"]},
    {"id":"CHEATING","bns":"318","ipc":"420","title":"Cheating","desc":"Deceiving a person dishonestly to induce delivery of property or altering/destroying valuable security.","punishment":"Up to 7 years + fine","keywords":"cheating fraud scam deceived duped con financial fraud swindled fake deal cheated money tricked false promise","defenses":["No dishonest intention","Civil dispute not cheating","Misunderstanding not deception","Breach of contract ≠ cheating"],"rights":["Right to file FIR","Right to approach Consumer Forum","Right to Legal Counsel"]},
    {"id":"FORGERY","bns":"336","ipc":"463/465","title":"Forgery","desc":"Making a false document with intent to cause damage, support a claim, or induce someone to part with property.","punishment":"Up to 2 years or fine or both","keywords":"forgery forged document fake signature false document counterfeit fabricated document fake certificate fake degree","defenses":["No fraudulent intent","Document was genuine","Mistake in preparation"],"rights":["Right to Legal Counsel","Right to document examination"]},

    # --- PART 2: PUBLIC ORDER, CYBER & MORE ---
    {"id":"CRIMINAL_INTIMIDATION","bns":"351","ipc":"503/506","title":"Criminal Intimidation","desc":"Threatening injury to person, reputation, or property to cause alarm or compel any act.","punishment":"Up to 2 years or fine. Death/grievous hurt threat: up to 7 years","keywords":"threat threatened threatening intimidation death threat life threat scare warned harm menace coerce","defenses":["Statement was warning not threat","No intent to cause alarm","Conditional and not immediate"],"rights":["Right to FIR","Right to Police Protection","Right to Legal Counsel"]},
    {"id":"CRIMINAL_TRESPASS","bns":"329","ipc":"441/447","title":"Criminal Trespass","desc":"Entering property in another's possession to commit offence, intimidate, insult or annoy.","punishment":"Up to 3 months or Rs.500 fine or both","keywords":"trespass entered property without permission unlawful entry encroachment land grabbing entered my house compound","defenses":["Right of way existed","Implied permission","No intent to offend","Claim of ownership"],"rights":["Right to FIR","Right to self-defense of property","Right to Legal Counsel"]},
    {"id":"MISCHIEF","bns":"324","ipc":"425/426","title":"Mischief / Property Damage","desc":"Causing destruction or damage to property with intent to cause wrongful loss or damage.","punishment":"Up to 3 months or fine or both. Fire/explosive: up to 7 years","keywords":"mischief property damage vandalism destroyed property damaged car broke windows smashed arson fire set fire burned crop","defenses":["Accident","No wrongful intent","Claim of right over property"],"rights":["Right to compensation","Right to FIR","Right to Legal Counsel"]},
    {"id":"DEFAMATION","bns":"356","ipc":"499/500","title":"Defamation","desc":"Making imputation to harm reputation by words, signs, or visible representations.","punishment":"Up to 2 years or fine or both","keywords":"defamation defame slander libel false accusation character assassination reputation damage fake news about me maligned name","defenses":["Truth for public good","Fair comment on public interest","Good faith belief","Privilege in court proceedings"],"rights":["Right to criminal + civil suit","Right to claim compensation","Right to Legal Counsel"]},
    {"id":"CYBERCRIME_HACKING","bns":"IT Act S.43/66","ipc":"IT Act + 463/468","title":"Hacking / Unauthorized Computer Access","desc":"Unauthorized access to computer system, data theft, introducing virus, damaging computer resources.","punishment":"Up to 3 years + fine up to Rs.5 lakh","keywords":"hacking hacked computer unauthorized access data breach virus malware system breach server hacked website defaced","defenses":["Had authorization","No criminal intent","Data was public","Ethical hacking/testing"],"rights":["Right to FIR at Cyber Cell","Right to data privacy","Right to Legal Counsel"]},
    {"id":"DOMESTIC_VIOLENCE","bns":"S.85-86 BNS + DV Act","ipc":"498A + DV Act 2005","title":"Domestic Violence / Cruelty by Husband","desc":"Physical, emotional, verbal, economic abuse or harassment of woman by husband or his relatives.","punishment":"Up to 3 years + fine under 498A. DV Act: Protection orders + compensation","keywords":"domestic violence wife beating husband abuse cruelty by husband in-laws torture matrimonial cruelty dowry harassment mental cruelty married woman harassed","defenses":["Mutual discord not cruelty","False complaint","No demand for dowry","Exaggerated claims"],"rights":["Right to file under DV Act 2005","Right to Protection Order","Right to shelter","Right to Maintenance (S.125 CrPC)","Right to free legal aid"]},
    {"id":"CHEQUE_BOUNCE","bns":"NI Act S.138","ipc":"Negotiable Instruments Act S.138","title":"Cheque Bounce / Dishonour","desc":"Cheque returned by bank due to insufficient funds or exceeding arrangement.","punishment":"Up to 2 years or twice the cheque amount or both","keywords":"cheque bounce dishonour cheque bounced insufficient funds payment stopped cheque returned NI Act bank returned cheque","defenses":["Cheque was not for legally enforceable debt","Payment made by other means","Cheque was stolen/forged","Notice not properly served"],"rights":["Right to send legal notice within 30 days","Right to file complaint within 1 month of notice expiry","Right to Legal Counsel"]},
    {"id":"ADULTERY","bns":"Decriminalized","ipc":"497 (Struck down 2018)","title":"Adultery","desc":"Adultery has been DECRIMINALIZED by Supreme Court in Joseph Shine v. Union of India (2018).","punishment":"DECRIMINALIZED - No criminal offence. Civil remedy for divorce available","keywords":"adultery extramarital affair cheating spouse husband wife affair illicit relationship infidelity","defenses":["No longer a criminal offence since 2018"],"rights":["Right to file for divorce on grounds of adultery","Civil remedy only","Right to Legal Counsel"]},
]

FUNDAMENTAL_RIGHTS = [
    "**Article 14**: Right to equality before law and equal protection of laws.",
    "**Article 19**: Right to freedom of speech, assembly, association, movement, residence, and profession.",
    "**Article 20(3)**: Right against self-incrimination — no person accused shall be compelled to be witness against himself.",
    "**Article 21**: Right to life and personal liberty — no deprivation except by procedure established by law.",
    "**Article 22(1)**: Right to be informed of grounds of arrest and right to consult a lawyer of choice.",
    "**Article 22(2)**: Right to be produced before nearest Magistrate within 24 hours of arrest.",
    "**Right to Free Legal Aid**: Under Article 39A and Section 304 CrPC — free legal counsel if cannot afford.",
    "**Right to Bail**: Bailable offences: bail is a right. Non-bailable: can be sought from Magistrate/Sessions Court.",
    "**Right to Fair Trial**: Right to be heard, present evidence, cross-examine witnesses, and appeal.",
]
