<<<<<<< HEAD
"""
Comprehensive BNS/IPC Legal Database - Part 2: Public Order, Cyber, Special Laws & More
"""

SECTIONS_PART2 = [
    {"id":"CRIMINAL_INTIMIDATION","bns":"351","ipc":"503/506","title":"Criminal Intimidation","desc":"Threatening injury to person, reputation, or property to cause alarm or compel any act.","punishment":"Up to 2 years or fine. Death/grievous hurt threat: up to 7 years","keywords":"threat threatened threatening intimidation death threat life threat scare warned harm menace coerce","defenses":["Statement was warning not threat","No intent to cause alarm","Conditional and not immediate"],"rights":["Right to FIR","Right to Police Protection","Right to Legal Counsel"]},
    {"id":"CRIMINAL_TRESPASS","bns":"329","ipc":"441/447","title":"Criminal Trespass","desc":"Entering property in another's possession to commit offence, intimidate, insult or annoy.","punishment":"Up to 3 months or Rs.500 fine or both","keywords":"trespass entered property without permission unlawful entry encroachment land grabbing entered my house compound","defenses":["Right of way existed","Implied permission","No intent to offend","Claim of ownership"],"rights":["Right to FIR","Right to self-defense of property","Right to Legal Counsel"]},
    {"id":"HOUSE_BREAKING","bns":"331","ipc":"453/456","title":"House Breaking / House Trespass","desc":"Committing house-trespass by breaking open or climbing into a dwelling house.","punishment":"Up to 2 years + fine. By night: up to 3 years + fine. For theft: up to 10 years","keywords":"house breaking break in broke into burglary broke door window someone entered house forcefully broke lock home invasion","defenses":["Had permission to enter","Bona fide claim to property","Door was open"],"rights":["Right to FIR","Right to compensation","Right to Legal Counsel"]},
    {"id":"MISCHIEF","bns":"324","ipc":"425/426","title":"Mischief / Property Damage","desc":"Causing destruction or damage to property with intent to cause wrongful loss or damage.","punishment":"Up to 3 months or fine or both. Fire/explosive: up to 7 years","keywords":"mischief property damage vandalism destroyed property damaged car broke windows smashed arson fire set fire burned crop","defenses":["Accident","No wrongful intent","Claim of right over property"],"rights":["Right to compensation","Right to FIR","Right to Legal Counsel"]},
    {"id":"DEFAMATION","bns":"356","ipc":"499/500","title":"Defamation","desc":"Making imputation to harm reputation by words, signs, or visible representations.","punishment":"Up to 2 years or fine or both","keywords":"defamation defame slander libel false accusation character assassination reputation damage fake news about me maligned name","defenses":["Truth for public good","Fair comment on public interest","Good faith belief","Privilege in court proceedings"],"rights":["Right to criminal + civil suit","Right to claim compensation","Right to Legal Counsel"]},
    {"id":"RIOTING","bns":"191","ipc":"146/147","title":"Rioting","desc":"Use of violence or force by unlawful assembly of 5 or more persons.","punishment":"Up to 2 years or fine or both. With deadly weapon: up to 3 years","keywords":"rioting riot mob violence unlawful assembly group violence public disturbance mob attack communal violence stone pelting","defenses":["Was not part of assembly","No common object","Was bystander not participant"],"rights":["Right to Legal Counsel","Right to Bail","Right to Fair Investigation"]},
    {"id":"AFFRAY","bns":"197","ipc":"159/160","title":"Affray","desc":"Two or more persons fighting in a public place disturbing public peace.","punishment":"Up to 1 month or Rs.100 fine or both","keywords":"affray public fight street fight brawl fighting in public disturbance of peace public quarrel","defenses":["Was acting in self-defense","Opponent was sole aggressor","Not in public place"],"rights":["Right to Bail (bailable)","Right to Legal Counsel"]},
    {"id":"PUBLIC_NUISANCE","bns":"292","ipc":"268/290","title":"Public Nuisance","desc":"Act causing common injury, danger, or annoyance to the public.","punishment":"Up to Rs.200 fine","keywords":"public nuisance noise pollution blocking road obstruction public annoyance environmental hazard dumping waste loud music late night","defenses":["Act was lawful","No annoyance caused","Private matter not public"],"rights":["Right to approach Magistrate","Right to civil remedy","Right to Legal Counsel"]},
    {"id":"DRUG_OFFENCE","bns":"NDPS Act","ipc":"NDPS Act S.20/21/22","title":"Drug Offences (NDPS Act)","desc":"Possession, sale, purchase, transport, or consumption of narcotic drugs or psychotropic substances.","punishment":"Small qty: up to 1 year. Commercial qty: 10-20 years + Rs.1-2 lakh fine","keywords":"drugs narcotics weed ganja marijuana cocaine heroin mdma drug possession drug trafficking ndps contraband charas opium brown sugar meth","defenses":["Planted evidence","No knowledge of substance","Personal consumption (reduced sentence)","Procedural violations in search (S.42/50 NDPS)"],"rights":["Right to search by gazetted officer (S.50)","Right to Legal Counsel","Right to de-addiction treatment (S.64A)"]},
    {"id":"CYBERCRIME_HACKING","bns":"IT Act S.43/66","ipc":"IT Act + 463/468","title":"Hacking / Unauthorized Computer Access","desc":"Unauthorized access to computer system, data theft, introducing virus, damaging computer resources.","punishment":"Up to 3 years + fine up to Rs.5 lakh","keywords":"hacking hacked computer unauthorized access data breach virus malware system breach server hacked website defaced","defenses":["Had authorization","No criminal intent","Data was public","Ethical hacking/testing"],"rights":["Right to FIR at Cyber Cell","Right to data privacy","Right to Legal Counsel"]},
    {"id":"CYBERCRIME_IDENTITY","bns":"IT Act S.66C","ipc":"IT Act S.66C","title":"Identity Theft (Cyber)","desc":"Fraudulently using electronic signature, password, or unique identification feature of another person.","punishment":"Up to 3 years + Rs.1 lakh fine","keywords":"identity theft impersonation online fake profile using my identity stolen identity phishing social media fake account someone using my name online","defenses":["No fraudulent use","Mistaken identity","Account was shared"],"rights":["Right to FIR at Cyber Crime Cell","Right to cybercrime.gov.in complaint","Right to Legal Counsel"]},
    {"id":"CYBERCRIME_OBSCENE","bns":"IT Act S.67","ipc":"IT Act S.67/67A/67B","title":"Publishing Obscene Content Online","desc":"Publishing or transmitting obscene material, sexually explicit content, or child pornography in electronic form.","punishment":"Obscene: up to 3 years + Rs.5 lakh. Sexually explicit: up to 5 years + Rs.10 lakh. Child porn: up to 7 years + Rs.10 lakh","keywords":"obscene content pornography revenge porn morphed photo nude leaked intimate images shared without consent sexting minor child pornography deepfake","defenses":["Content was not obscene","No transmission occurred","False accusation"],"rights":["Victim: Right to removal of content","Right to FIR","Right to Legal Counsel"]},
    {"id":"CYBER_FRAUD","bns":"IT Act + S.318 BNS","ipc":"IT Act + 420","title":"Online/Cyber Fraud","desc":"Cheating through electronic means - fake websites, UPI fraud, phishing, online shopping fraud.","punishment":"Up to 7 years + fine (Cheating) + IT Act penalties","keywords":"online fraud cyber fraud UPI fraud phishing email scam fake website OTP fraud internet banking fraud credit card fraud e-commerce fraud online shopping scam","defenses":["No dishonest intention","Technical error not fraud","Legitimate transaction"],"rights":["Right to FIR at Cyber Cell","File at cybercrime.gov.in","Right to compensation","Right to Legal Counsel"]},
    {"id":"DOMESTIC_VIOLENCE","bns":"S.85-86 BNS + DV Act","ipc":"498A + DV Act 2005","title":"Domestic Violence / Cruelty by Husband","desc":"Physical, emotional, verbal, economic abuse or harassment of woman by husband or his relatives.","punishment":"Up to 3 years + fine under 498A. DV Act: Protection orders + compensation","keywords":"domestic violence wife beating husband abuse cruelty by husband in-laws torture matrimonial cruelty dowry harassment mental cruelty married woman harassed","defenses":["Mutual discord not cruelty","False complaint","No demand for dowry","Exaggerated claims"],"rights":["Right to file under DV Act 2005","Right to Protection Order","Right to shelter","Right to Maintenance (S.125 CrPC)","Right to free legal aid"]},
    {"id":"CHILD_ABUSE","bns":"BNS + POCSO Act","ipc":"IPC + POCSO Act 2012","title":"Child Sexual Abuse (POCSO)","desc":"Sexual assault, harassment, or exploitation of child under 18 years.","punishment":"Penetrative assault: 10 years to Life. Aggravated: 20 years to Life. Non-penetrative: 3-5 years","keywords":"child abuse child sexual abuse POCSO minor abuse child molestation child rape child exploitation child pornography minor sexually abused","defenses":["Age of victim disputed","False implication","No such act occurred"],"rights":["Child: Right to child-friendly court","Child: Special Public Prosecutor","Child: Identity protection","Mandatory reporting by institutions"]},
    {"id":"SC_ST_ATROCITY","bns":"SC/ST Act 1989","ipc":"SC/ST Prevention of Atrocities Act","title":"Atrocities Against SC/ST","desc":"Offences committed against Scheduled Caste/Tribe members based on caste discrimination.","punishment":"6 months to 5 years + fine. Severe cases: Life imprisonment","keywords":"caste discrimination SC ST atrocity dalit harassment untouchability caste abuse scheduled caste scheduled tribe caste violence caste slur","defenses":["No caste-based intent","Prior enmity unrelated to caste","False implication"],"rights":["Right to immediate FIR (non-bailable)","Right to special court trial","Right to compensation","Right to investigation by DSP rank officer"]},
    {"id":"CORRUPTION","bns":"Prevention of Corruption Act","ipc":"PC Act 1988","title":"Corruption / Bribery by Public Servant","desc":"Public servant accepting or demanding illegal gratification for performing official duty.","punishment":"3-7 years + fine","keywords":"corruption bribe bribery government officer demanding money for work public servant corrupt official kickback under table gratification","defenses":["No demand was made","Trap was fabricated","Money was loan not bribe"],"rights":["Right to file complaint with ACB/CBI","Right to Lokpal/Lokayukta","Right to RTI for tracking"]},
    {"id":"SEDITION","bns":"152","ipc":"124A (repealed)","title":"Acts Endangering Sovereignty / Sedition","desc":"Acts that endanger sovereignty, unity, and integrity of India through words, signs, or visible representation.","punishment":"Up to Life imprisonment or up to 7 years + fine","keywords":"sedition anti national sovereignty unity integrity separatism secession inciting disaffection against state government","defenses":["Freedom of speech (Art.19)","Criticism is not sedition","Academic/literary expression"],"rights":["Right to Free Speech (Art 19)","Right to Legal Counsel","Right to Bail"]},
    {"id":"WAGING_WAR","bns":"147","ipc":"121","title":"Waging War Against India","desc":"Waging or attempting to wage war against the Government of India.","punishment":"Death or Life imprisonment + fine","keywords":"waging war against India terrorism treason armed rebellion insurrection attacking government anti-India war","defenses":["No overt act of war","No intention to wage war","Political protest not war"],"rights":["Right to Legal Counsel","Right to Fair Trial"]},
    {"id":"ATTEMPT_SUICIDE","bns":"Decriminalized","ipc":"309 (Repealed by MH Act 2017)","title":"Attempt to Suicide","desc":"Attempt to commit suicide is DECRIMINALIZED. Person must be treated as someone in need of care.","punishment":"DECRIMINALIZED - No punishment. Person entitled to care and rehabilitation","keywords":"attempt suicide tried suicide self harm suicidal attempted suicide mental health depression suicide attempt","defenses":["This is no longer a criminal offence","Person needs medical help not prosecution"],"rights":["Right to mental healthcare","Right to rehabilitation","Right to insurance coverage","No criminal prosecution under MH Act 2017"]},
    {"id":"BIGAMY","bns":"82","ipc":"494","title":"Bigamy","desc":"Marrying again during lifetime of husband or wife without valid divorce.","punishment":"Up to 7 years + fine","keywords":"bigamy second marriage married again husband married another wife married another already married polygamy remarriage without divorce","defenses":["First marriage was void","First spouse declared dead (7+ years absent)","Valid divorce obtained"],"rights":["Right to file complaint by aggrieved spouse","Right to maintenance","Right to Legal Counsel"]},
    {"id":"ADULTERY","bns":"Decriminalized","ipc":"497 (Struck down 2018)","title":"Adultery","desc":"Adultery has been DECRIMINALIZED by Supreme Court in Joseph Shine v. Union of India (2018).","punishment":"DECRIMINALIZED - No criminal offence. Civil remedy for divorce available","keywords":"adultery extramarital affair cheating spouse husband wife affair illicit relationship infidelity","defenses":["No longer a criminal offence since 2018"],"rights":["Right to file for divorce on grounds of adultery","Civil remedy only","Right to Legal Counsel"]},
    {"id":"CRUELTY_ANIMALS","bns":"PCA Act 1960","ipc":"PCA Act + 428/429 IPC","title":"Cruelty to Animals","desc":"Causing unnecessary suffering, beating, overloading, or killing animals cruelly.","punishment":"First offence: Rs.10-50 fine. Repeat: Rs.25-100 + up to 3 months. Killing valuable animal (IPC): up to 5 years","keywords":"animal cruelty animal abuse dog beating cat killing stray dog animal torture poisoning animals cattle cruelty horse abuse pet abuse","defenses":["Act was necessary (veterinary)","Self-defense against dangerous animal","Accidental harm"],"rights":["Right to report to Animal Welfare Board","Right to file FIR","Right to approach SPCA"]},
    {"id":"CHEQUE_BOUNCE","bns":"NI Act S.138","ipc":"Negotiable Instruments Act S.138","title":"Cheque Bounce / Dishonour","desc":"Cheque returned by bank due to insufficient funds or exceeding arrangement.","punishment":"Up to 2 years or twice the cheque amount or both","keywords":"cheque bounce dishonour cheque bounced insufficient funds payment stopped cheque returned NI Act bank returned cheque","defenses":["Cheque was not for legally enforceable debt","Payment made by other means","Cheque was stolen/forged","Notice not properly served"],"rights":["Right to send legal notice within 30 days","Right to file complaint within 1 month of notice expiry","Right to Legal Counsel"]},
    {"id":"MOTOR_ACCIDENT","bns":"S.106 BNS","ipc":"304A","title":"Death by Rash/Negligent Driving","desc":"Causing death by rash or negligent act, including motor vehicle accidents.","punishment":"Up to 5 years + fine. Hit and run: enhanced penalties under MV Act","keywords":"road accident hit and run rash driving negligent driving car accident vehicle accident death by driving drunk driving running over pedestrian killed by vehicle","defenses":["Victim's own negligence","Mechanical failure","Act of God","No rashness or negligence"],"rights":["Right to compensation under MV Act","Right to Legal Counsel","Right to Bail","Victim: Right to Motor Accident Claims Tribunal"]},
    {"id":"OBSCENITY","bns":"294 BNS","ipc":"292/294","title":"Obscenity / Obscene Acts in Public","desc":"Doing any obscene act in public place, or selling/distributing obscene material.","punishment":"Up to 3 months or fine or both. Sale of obscene material: up to 2 years + fine","keywords":"obscenity public indecency nude in public obscene act obscene material indecent exposure flashing public urination obscene gestures","defenses":["Act was not obscene by community standards","Not in public view","Artistic/literary merit"],"rights":["Right to Legal Counsel","Right to Bail"]},
    {"id":"UNLAWFUL_ASSEMBLY","bns":"189","ipc":"141/143","title":"Unlawful Assembly","desc":"Assembly of 5+ persons with common object to commit offence, resist lawful process, or criminal trespass.","punishment":"Up to 6 months or fine or both","keywords":"unlawful assembly illegal gathering mob protest turned violent group of people causing trouble common intention mob justice lynching","defenses":["Was peaceful assembly (Art.19)","Was not member of assembly","No common unlawful object"],"rights":["Right to peaceful assembly (Art 19)","Right to Legal Counsel","Right to Bail"]},
    {"id":"FALSE_EVIDENCE","bns":"229","ipc":"191/193","title":"Giving False Evidence / Perjury","desc":"Making false statement under oath, fabricating false evidence.","punishment":"Up to 7 years + fine","keywords":"false evidence perjury lying in court fabricated evidence planted evidence false testimony fake witness false oath false affidavit","defenses":["Statement was true to best of knowledge","Honest mistake not perjury","Retraction of statement"],"rights":["Right to Legal Counsel","Right to cross-examine"]},
    {"id":"FALSE_FIR","bns":"248","ipc":"182/211","title":"Filing False FIR / False Criminal Complaint","desc":"Giving false information with intent to cause public servant to use lawful power to injure another.","punishment":"S.182: up to 6 months or Rs.1000 fine. S.211: up to 2 years or fine","keywords":"false FIR false complaint fake case lodged against me false accusation malicious prosecution false charge fabricated case framed wrongly accused","defenses":["Complaint was genuine","Reasonable belief of offence","Not filed with mala fide intent"],"rights":["Right to file counter-complaint","Right to claim damages","Right to quashing of FIR (S.482 CrPC)","Right to Legal Counsel"]},
    {"id":"CONTEMPT_COURT","bns":"Contempt of Courts Act 1971","ipc":"Contempt of Courts Act","title":"Contempt of Court","desc":"Willful disobedience of court order or any act that scandalises or lowers authority of court.","punishment":"Up to 6 months or Rs.2000 fine or both","keywords":"contempt of court disobeying court order disrespecting judge violating court order insulting court not following court direction","defenses":["Fair & accurate reporting","Fair criticism of judicial act","Truth as defense (with court's leave)"],"rights":["Right to apologize and purge contempt","Right to Legal Counsel","Right to Appeal"]},
]

# Universal Fundamental Rights
FUNDAMENTAL_RIGHTS = [
    "**Article 14**: Right to equality before law and equal protection of laws.",
    "**Article 19**: Right to freedom of speech, assembly, association, movement, residence, and profession.",
    "**Article 20(1)**: No ex-post-facto criminal law — cannot be convicted for act not an offence when committed.",
    "**Article 20(3)**: Right against self-incrimination — no person accused shall be compelled to be witness against himself.",
    "**Article 21**: Right to life and personal liberty — no deprivation except by procedure established by law.",
    "**Article 22(1)**: Right to be informed of grounds of arrest and right to consult a lawyer of choice.",
    "**Article 22(2)**: Right to be produced before nearest Magistrate within 24 hours of arrest.",
    "**Section 41A CrPC**: Police must issue notice before arrest for offences up to 7 years imprisonment.",
    "**Right to Free Legal Aid**: Under Article 39A and Section 304 CrPC — free legal counsel if cannot afford.",
    "**Right to Bail**: Bailable offences: bail is a right. Non-bailable: can be sought from Magistrate/Sessions Court.",
    "**Right to Fair Trial**: Right to be heard, present evidence, cross-examine witnesses, and appeal.",
    "**Right to Speedy Trial**: Derived from Article 21 — unreasonable delay violates fundamental rights.",
    "**Right to Know Charges**: Every accused must be informed of the specific charges and sections applied.",
    "**Right to Silence**: Accused can refuse to answer questions during interrogation.",
    "**Right to Human Dignity**: No torture, degrading treatment during investigation or custody (D.K. Basu guidelines)."
]
=======
"""
Comprehensive BNS/IPC Legal Database - Part 2: Public Order, Cyber, Special Laws & More
"""

SECTIONS_PART2 = [
    {"id":"CRIMINAL_INTIMIDATION","bns":"351","ipc":"503/506","title":"Criminal Intimidation","desc":"Threatening injury to person, reputation, or property to cause alarm or compel any act.","punishment":"Up to 2 years or fine. Death/grievous hurt threat: up to 7 years","keywords":"threat threatened threatening intimidation death threat life threat scare warned harm menace coerce","defenses":["Statement was warning not threat","No intent to cause alarm","Conditional and not immediate"],"rights":["Right to FIR","Right to Police Protection","Right to Legal Counsel"]},
    {"id":"CRIMINAL_TRESPASS","bns":"329","ipc":"441/447","title":"Criminal Trespass","desc":"Entering property in another's possession to commit offence, intimidate, insult or annoy.","punishment":"Up to 3 months or Rs.500 fine or both","keywords":"trespass entered property without permission unlawful entry encroachment land grabbing entered my house compound","defenses":["Right of way existed","Implied permission","No intent to offend","Claim of ownership"],"rights":["Right to FIR","Right to self-defense of property","Right to Legal Counsel"]},
    {"id":"HOUSE_BREAKING","bns":"331","ipc":"453/456","title":"House Breaking / House Trespass","desc":"Committing house-trespass by breaking open or climbing into a dwelling house.","punishment":"Up to 2 years + fine. By night: up to 3 years + fine. For theft: up to 10 years","keywords":"house breaking break in broke into burglary broke door window someone entered house forcefully broke lock home invasion","defenses":["Had permission to enter","Bona fide claim to property","Door was open"],"rights":["Right to FIR","Right to compensation","Right to Legal Counsel"]},
    {"id":"MISCHIEF","bns":"324","ipc":"425/426","title":"Mischief / Property Damage","desc":"Causing destruction or damage to property with intent to cause wrongful loss or damage.","punishment":"Up to 3 months or fine or both. Fire/explosive: up to 7 years","keywords":"mischief property damage vandalism destroyed property damaged car broke windows smashed arson fire set fire burned crop","defenses":["Accident","No wrongful intent","Claim of right over property"],"rights":["Right to compensation","Right to FIR","Right to Legal Counsel"]},
    {"id":"DEFAMATION","bns":"356","ipc":"499/500","title":"Defamation","desc":"Making imputation to harm reputation by words, signs, or visible representations.","punishment":"Up to 2 years or fine or both","keywords":"defamation defame slander libel false accusation character assassination reputation damage fake news about me maligned name","defenses":["Truth for public good","Fair comment on public interest","Good faith belief","Privilege in court proceedings"],"rights":["Right to criminal + civil suit","Right to claim compensation","Right to Legal Counsel"]},
    {"id":"RIOTING","bns":"191","ipc":"146/147","title":"Rioting","desc":"Use of violence or force by unlawful assembly of 5 or more persons.","punishment":"Up to 2 years or fine or both. With deadly weapon: up to 3 years","keywords":"rioting riot mob violence unlawful assembly group violence public disturbance mob attack communal violence stone pelting","defenses":["Was not part of assembly","No common object","Was bystander not participant"],"rights":["Right to Legal Counsel","Right to Bail","Right to Fair Investigation"]},
    {"id":"AFFRAY","bns":"197","ipc":"159/160","title":"Affray","desc":"Two or more persons fighting in a public place disturbing public peace.","punishment":"Up to 1 month or Rs.100 fine or both","keywords":"affray public fight street fight brawl fighting in public disturbance of peace public quarrel","defenses":["Was acting in self-defense","Opponent was sole aggressor","Not in public place"],"rights":["Right to Bail (bailable)","Right to Legal Counsel"]},
    {"id":"PUBLIC_NUISANCE","bns":"292","ipc":"268/290","title":"Public Nuisance","desc":"Act causing common injury, danger, or annoyance to the public.","punishment":"Up to Rs.200 fine","keywords":"public nuisance noise pollution blocking road obstruction public annoyance environmental hazard dumping waste loud music late night","defenses":["Act was lawful","No annoyance caused","Private matter not public"],"rights":["Right to approach Magistrate","Right to civil remedy","Right to Legal Counsel"]},
    {"id":"DRUG_OFFENCE","bns":"NDPS Act","ipc":"NDPS Act S.20/21/22","title":"Drug Offences (NDPS Act)","desc":"Possession, sale, purchase, transport, or consumption of narcotic drugs or psychotropic substances.","punishment":"Small qty: up to 1 year. Commercial qty: 10-20 years + Rs.1-2 lakh fine","keywords":"drugs narcotics weed ganja marijuana cocaine heroin mdma drug possession drug trafficking ndps contraband charas opium brown sugar meth","defenses":["Planted evidence","No knowledge of substance","Personal consumption (reduced sentence)","Procedural violations in search (S.42/50 NDPS)"],"rights":["Right to search by gazetted officer (S.50)","Right to Legal Counsel","Right to de-addiction treatment (S.64A)"]},
    {"id":"CYBERCRIME_HACKING","bns":"IT Act S.43/66","ipc":"IT Act + 463/468","title":"Hacking / Unauthorized Computer Access","desc":"Unauthorized access to computer system, data theft, introducing virus, damaging computer resources.","punishment":"Up to 3 years + fine up to Rs.5 lakh","keywords":"hacking hacked computer unauthorized access data breach virus malware system breach server hacked website defaced","defenses":["Had authorization","No criminal intent","Data was public","Ethical hacking/testing"],"rights":["Right to FIR at Cyber Cell","Right to data privacy","Right to Legal Counsel"]},
    {"id":"CYBERCRIME_IDENTITY","bns":"IT Act S.66C","ipc":"IT Act S.66C","title":"Identity Theft (Cyber)","desc":"Fraudulently using electronic signature, password, or unique identification feature of another person.","punishment":"Up to 3 years + Rs.1 lakh fine","keywords":"identity theft impersonation online fake profile using my identity stolen identity phishing social media fake account someone using my name online","defenses":["No fraudulent use","Mistaken identity","Account was shared"],"rights":["Right to FIR at Cyber Crime Cell","Right to cybercrime.gov.in complaint","Right to Legal Counsel"]},
    {"id":"CYBERCRIME_OBSCENE","bns":"IT Act S.67","ipc":"IT Act S.67/67A/67B","title":"Publishing Obscene Content Online","desc":"Publishing or transmitting obscene material, sexually explicit content, or child pornography in electronic form.","punishment":"Obscene: up to 3 years + Rs.5 lakh. Sexually explicit: up to 5 years + Rs.10 lakh. Child porn: up to 7 years + Rs.10 lakh","keywords":"obscene content pornography revenge porn morphed photo nude leaked intimate images shared without consent sexting minor child pornography deepfake","defenses":["Content was not obscene","No transmission occurred","False accusation"],"rights":["Victim: Right to removal of content","Right to FIR","Right to Legal Counsel"]},
    {"id":"CYBER_FRAUD","bns":"IT Act + S.318 BNS","ipc":"IT Act + 420","title":"Online/Cyber Fraud","desc":"Cheating through electronic means - fake websites, UPI fraud, phishing, online shopping fraud.","punishment":"Up to 7 years + fine (Cheating) + IT Act penalties","keywords":"online fraud cyber fraud UPI fraud phishing email scam fake website OTP fraud internet banking fraud credit card fraud e-commerce fraud online shopping scam","defenses":["No dishonest intention","Technical error not fraud","Legitimate transaction"],"rights":["Right to FIR at Cyber Cell","File at cybercrime.gov.in","Right to compensation","Right to Legal Counsel"]},
    {"id":"DOMESTIC_VIOLENCE","bns":"S.85-86 BNS + DV Act","ipc":"498A + DV Act 2005","title":"Domestic Violence / Cruelty by Husband","desc":"Physical, emotional, verbal, economic abuse or harassment of woman by husband or his relatives.","punishment":"Up to 3 years + fine under 498A. DV Act: Protection orders + compensation","keywords":"domestic violence wife beating husband abuse cruelty by husband in-laws torture matrimonial cruelty dowry harassment mental cruelty married woman harassed","defenses":["Mutual discord not cruelty","False complaint","No demand for dowry","Exaggerated claims"],"rights":["Right to file under DV Act 2005","Right to Protection Order","Right to shelter","Right to Maintenance (S.125 CrPC)","Right to free legal aid"]},
    {"id":"CHILD_ABUSE","bns":"BNS + POCSO Act","ipc":"IPC + POCSO Act 2012","title":"Child Sexual Abuse (POCSO)","desc":"Sexual assault, harassment, or exploitation of child under 18 years.","punishment":"Penetrative assault: 10 years to Life. Aggravated: 20 years to Life. Non-penetrative: 3-5 years","keywords":"child abuse child sexual abuse POCSO minor abuse child molestation child rape child exploitation child pornography minor sexually abused","defenses":["Age of victim disputed","False implication","No such act occurred"],"rights":["Child: Right to child-friendly court","Child: Special Public Prosecutor","Child: Identity protection","Mandatory reporting by institutions"]},
    {"id":"SC_ST_ATROCITY","bns":"SC/ST Act 1989","ipc":"SC/ST Prevention of Atrocities Act","title":"Atrocities Against SC/ST","desc":"Offences committed against Scheduled Caste/Tribe members based on caste discrimination.","punishment":"6 months to 5 years + fine. Severe cases: Life imprisonment","keywords":"caste discrimination SC ST atrocity dalit harassment untouchability caste abuse scheduled caste scheduled tribe caste violence caste slur","defenses":["No caste-based intent","Prior enmity unrelated to caste","False implication"],"rights":["Right to immediate FIR (non-bailable)","Right to special court trial","Right to compensation","Right to investigation by DSP rank officer"]},
    {"id":"CORRUPTION","bns":"Prevention of Corruption Act","ipc":"PC Act 1988","title":"Corruption / Bribery by Public Servant","desc":"Public servant accepting or demanding illegal gratification for performing official duty.","punishment":"3-7 years + fine","keywords":"corruption bribe bribery government officer demanding money for work public servant corrupt official kickback under table gratification","defenses":["No demand was made","Trap was fabricated","Money was loan not bribe"],"rights":["Right to file complaint with ACB/CBI","Right to Lokpal/Lokayukta","Right to RTI for tracking"]},
    {"id":"SEDITION","bns":"152","ipc":"124A (repealed)","title":"Acts Endangering Sovereignty / Sedition","desc":"Acts that endanger sovereignty, unity, and integrity of India through words, signs, or visible representation.","punishment":"Up to Life imprisonment or up to 7 years + fine","keywords":"sedition anti national sovereignty unity integrity separatism secession inciting disaffection against state government","defenses":["Freedom of speech (Art.19)","Criticism is not sedition","Academic/literary expression"],"rights":["Right to Free Speech (Art 19)","Right to Legal Counsel","Right to Bail"]},
    {"id":"WAGING_WAR","bns":"147","ipc":"121","title":"Waging War Against India","desc":"Waging or attempting to wage war against the Government of India.","punishment":"Death or Life imprisonment + fine","keywords":"waging war against India terrorism treason armed rebellion insurrection attacking government anti-India war","defenses":["No overt act of war","No intention to wage war","Political protest not war"],"rights":["Right to Legal Counsel","Right to Fair Trial"]},
    {"id":"ATTEMPT_SUICIDE","bns":"Decriminalized","ipc":"309 (Repealed by MH Act 2017)","title":"Attempt to Suicide","desc":"Attempt to commit suicide is DECRIMINALIZED. Person must be treated as someone in need of care.","punishment":"DECRIMINALIZED - No punishment. Person entitled to care and rehabilitation","keywords":"attempt suicide tried suicide self harm suicidal attempted suicide mental health depression suicide attempt","defenses":["This is no longer a criminal offence","Person needs medical help not prosecution"],"rights":["Right to mental healthcare","Right to rehabilitation","Right to insurance coverage","No criminal prosecution under MH Act 2017"]},
    {"id":"BIGAMY","bns":"82","ipc":"494","title":"Bigamy","desc":"Marrying again during lifetime of husband or wife without valid divorce.","punishment":"Up to 7 years + fine","keywords":"bigamy second marriage married again husband married another wife married another already married polygamy remarriage without divorce","defenses":["First marriage was void","First spouse declared dead (7+ years absent)","Valid divorce obtained"],"rights":["Right to file complaint by aggrieved spouse","Right to maintenance","Right to Legal Counsel"]},
    {"id":"ADULTERY","bns":"Decriminalized","ipc":"497 (Struck down 2018)","title":"Adultery","desc":"Adultery has been DECRIMINALIZED by Supreme Court in Joseph Shine v. Union of India (2018).","punishment":"DECRIMINALIZED - No criminal offence. Civil remedy for divorce available","keywords":"adultery extramarital affair cheating spouse husband wife affair illicit relationship infidelity","defenses":["No longer a criminal offence since 2018"],"rights":["Right to file for divorce on grounds of adultery","Civil remedy only","Right to Legal Counsel"]},
    {"id":"CRUELTY_ANIMALS","bns":"PCA Act 1960","ipc":"PCA Act + 428/429 IPC","title":"Cruelty to Animals","desc":"Causing unnecessary suffering, beating, overloading, or killing animals cruelly.","punishment":"First offence: Rs.10-50 fine. Repeat: Rs.25-100 + up to 3 months. Killing valuable animal (IPC): up to 5 years","keywords":"animal cruelty animal abuse dog beating cat killing stray dog animal torture poisoning animals cattle cruelty horse abuse pet abuse","defenses":["Act was necessary (veterinary)","Self-defense against dangerous animal","Accidental harm"],"rights":["Right to report to Animal Welfare Board","Right to file FIR","Right to approach SPCA"]},
    {"id":"CHEQUE_BOUNCE","bns":"NI Act S.138","ipc":"Negotiable Instruments Act S.138","title":"Cheque Bounce / Dishonour","desc":"Cheque returned by bank due to insufficient funds or exceeding arrangement.","punishment":"Up to 2 years or twice the cheque amount or both","keywords":"cheque bounce dishonour cheque bounced insufficient funds payment stopped cheque returned NI Act bank returned cheque","defenses":["Cheque was not for legally enforceable debt","Payment made by other means","Cheque was stolen/forged","Notice not properly served"],"rights":["Right to send legal notice within 30 days","Right to file complaint within 1 month of notice expiry","Right to Legal Counsel"]},
    {"id":"MOTOR_ACCIDENT","bns":"S.106 BNS","ipc":"304A","title":"Death by Rash/Negligent Driving","desc":"Causing death by rash or negligent act, including motor vehicle accidents.","punishment":"Up to 5 years + fine. Hit and run: enhanced penalties under MV Act","keywords":"road accident hit and run rash driving negligent driving car accident vehicle accident death by driving drunk driving running over pedestrian killed by vehicle","defenses":["Victim's own negligence","Mechanical failure","Act of God","No rashness or negligence"],"rights":["Right to compensation under MV Act","Right to Legal Counsel","Right to Bail","Victim: Right to Motor Accident Claims Tribunal"]},
    {"id":"OBSCENITY","bns":"294 BNS","ipc":"292/294","title":"Obscenity / Obscene Acts in Public","desc":"Doing any obscene act in public place, or selling/distributing obscene material.","punishment":"Up to 3 months or fine or both. Sale of obscene material: up to 2 years + fine","keywords":"obscenity public indecency nude in public obscene act obscene material indecent exposure flashing public urination obscene gestures","defenses":["Act was not obscene by community standards","Not in public view","Artistic/literary merit"],"rights":["Right to Legal Counsel","Right to Bail"]},
    {"id":"UNLAWFUL_ASSEMBLY","bns":"189","ipc":"141/143","title":"Unlawful Assembly","desc":"Assembly of 5+ persons with common object to commit offence, resist lawful process, or criminal trespass.","punishment":"Up to 6 months or fine or both","keywords":"unlawful assembly illegal gathering mob protest turned violent group of people causing trouble common intention mob justice lynching","defenses":["Was peaceful assembly (Art.19)","Was not member of assembly","No common unlawful object"],"rights":["Right to peaceful assembly (Art 19)","Right to Legal Counsel","Right to Bail"]},
    {"id":"FALSE_EVIDENCE","bns":"229","ipc":"191/193","title":"Giving False Evidence / Perjury","desc":"Making false statement under oath, fabricating false evidence.","punishment":"Up to 7 years + fine","keywords":"false evidence perjury lying in court fabricated evidence planted evidence false testimony fake witness false oath false affidavit","defenses":["Statement was true to best of knowledge","Honest mistake not perjury","Retraction of statement"],"rights":["Right to Legal Counsel","Right to cross-examine"]},
    {"id":"FALSE_FIR","bns":"248","ipc":"182/211","title":"Filing False FIR / False Criminal Complaint","desc":"Giving false information with intent to cause public servant to use lawful power to injure another.","punishment":"S.182: up to 6 months or Rs.1000 fine. S.211: up to 2 years or fine","keywords":"false FIR false complaint fake case lodged against me false accusation malicious prosecution false charge fabricated case framed wrongly accused","defenses":["Complaint was genuine","Reasonable belief of offence","Not filed with mala fide intent"],"rights":["Right to file counter-complaint","Right to claim damages","Right to quashing of FIR (S.482 CrPC)","Right to Legal Counsel"]},
    {"id":"CONTEMPT_COURT","bns":"Contempt of Courts Act 1971","ipc":"Contempt of Courts Act","title":"Contempt of Court","desc":"Willful disobedience of court order or any act that scandalises or lowers authority of court.","punishment":"Up to 6 months or Rs.2000 fine or both","keywords":"contempt of court disobeying court order disrespecting judge violating court order insulting court not following court direction","defenses":["Fair & accurate reporting","Fair criticism of judicial act","Truth as defense (with court's leave)"],"rights":["Right to apologize and purge contempt","Right to Legal Counsel","Right to Appeal"]},
]

# Universal Fundamental Rights
FUNDAMENTAL_RIGHTS = [
    "**Article 14**: Right to equality before law and equal protection of laws.",
    "**Article 19**: Right to freedom of speech, assembly, association, movement, residence, and profession.",
    "**Article 20(1)**: No ex-post-facto criminal law — cannot be convicted for act not an offence when committed.",
    "**Article 20(3)**: Right against self-incrimination — no person accused shall be compelled to be witness against himself.",
    "**Article 21**: Right to life and personal liberty — no deprivation except by procedure established by law.",
    "**Article 22(1)**: Right to be informed of grounds of arrest and right to consult a lawyer of choice.",
    "**Article 22(2)**: Right to be produced before nearest Magistrate within 24 hours of arrest.",
    "**Section 41A CrPC**: Police must issue notice before arrest for offences up to 7 years imprisonment.",
    "**Right to Free Legal Aid**: Under Article 39A and Section 304 CrPC — free legal counsel if cannot afford.",
    "**Right to Bail**: Bailable offences: bail is a right. Non-bailable: can be sought from Magistrate/Sessions Court.",
    "**Right to Fair Trial**: Right to be heard, present evidence, cross-examine witnesses, and appeal.",
    "**Right to Speedy Trial**: Derived from Article 21 — unreasonable delay violates fundamental rights.",
    "**Right to Know Charges**: Every accused must be informed of the specific charges and sections applied.",
    "**Right to Silence**: Accused can refuse to answer questions during interrogation.",
    "**Right to Human Dignity**: No torture, degrading treatment during investigation or custody (D.K. Basu guidelines)."
]
>>>>>>> d2165740c73ef4c6d4a2639a12e4eddbb03146c0
